spring.application.name=easy

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ====================== DATABASE ======================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/easy_market}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# ====================== JPA ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ====================== JWT ======================
jwt.secret=${JWT_SECRET:SuperSecretKeyForVisionApp2026VeryLongAndComplex123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ====================== Server ======================
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# =======================
# REDIS
# =======================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# EMAIL CONFIGURATION (pour OTP)
# =======================
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.from=${MAIL_FROM_ADDRESS:noreply@easy-api.com}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

cors.allowed-origins=*